#! /bin/sh

if [ $# -lt 3 -o "x$1" != "x-o" ]
then
    echo "usage: armdsp-link -o output file.obj ..."
    exit 1
fi

shift
outname=$1
shift

elfname=${outname}.elf

adir=/usr/local/armdsp

cl6x --abi=eabi \
    -z ${adir}/dsp/armdsp-link.cmd \
    --output_file ${elfname} \
    ${adir}/dsp/vecs.obj \
    ${adir}/dsp/dsptrg.obj \
    $*
ret=$?
if [ $ret != 0 ]
then
    exit $ret
fi

x=`nm6x ${elfname} | grep '^80000000 . vector_table$'`
if [ -z "$x" ]
then
    echo "armdsp-link: vector_table not allocated properly"
    exit 1
fi

hex6x -q -m --order=M --romwidth=32 -o=${outname}.srec ${elfname}
ret=$?
if [ $ret != 0 ]
then
    echo $ret
fi

$adir/bin/armdsp-mkais ${outname}.srec ${outname}


