#ifndef _DSPLOADER_H_
#define _DSPLOADER_H_

#define DSPLOADER_IOC_MAGIC  'd'
#define DSPLOADER_IOCSTOP _IO(DSPLOADER_IOC_MAGIC, 47)
#define DSPLOADER_IOCSTART _IO(DSPLOADER_IOC_MAGIC, 48)

#endif /* _DSPLOADER_H_ */
