# -*- mode:Makefile -*-
ARMDSP_DIR=/usr/local/armdsp
ARM_CROSS_COMPILE=arm-none-linux-gnueabi-
ARMCC = $(ARM_CROSS_COMPILE)gcc -g -Wall -I$(ARMDSP_DIR)/include \
	-L$(ARMDSP_DIR)/arm/lib
CL6X = cl6x

# it's safe to add --mem_model here if you want other than the default
CL6X_FLAGS = --abi=eabi -I$(ARMDSP_DIR)/include

.SUFFIXES: .obj .asm

.c.obj:
	$(CL6X) $(CL6X_FLAGS) -c $*.c

.asm.obj:
	$(CL6X) $(CL6X_FLAGS) -c $*.asm

ARMDSP_LINK = $(ARMDSP_DIR)/bin/armdsp-link
