# -*- mode:Makefile -*-
ARMDSP_DIR=/usr/local/armdsp
ARMCC = arm-none-linux-gnueabi-gcc -g -Wall -I$(ARMDSP_DIR)/include
CL6X = cl6x

# it's safe to use --mem_model here if you want other than the default
CL6X_FLAGS = --abi=eabi \
	--symdebug:none \
	-I$(ARMDSP_DIR)/include

.SUFFIXES: .obj .asm

.c.obj:
	$(CL6X) $(CL6X_FLAGS) -c $*.c

.asm.obj:
	$(CL6X) $(CL6X_FLAGS) -c $*.asm

ARMDSP_LINK = $(ARMDSP_DIR)/bin/armdsp-link
